-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : db
-- Généré le : jeu. 22 mai 2025 à 09:19
-- Version du serveur : 11.5.2-MariaDB-ubu2404
-- Version de PHP : 8.2.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `vibropolis`
--

-- --------------------------------------------------------

--
-- Structure de la table `Artiste`
--

CREATE TABLE `Artiste` (
  `id` int(11) NOT NULL,
  `nom` varchar(191) NOT NULL,
  `description` varchar(900) NOT NULL,
  `photo` varchar(191) NOT NULL,
  `datePerformance` datetime(3) NOT NULL,
  `couleur` varchar(191) DEFAULT NULL,
  `instagram` varchar(191) DEFAULT NULL,
  `spotify` varchar(191) DEFAULT NULL,
  `tiktok` varchar(191) DEFAULT NULL,
  `youtube` varchar(191) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `Artiste`
--

INSERT INTO `Artiste` (`id`, `nom`, `description`, `photo`, `datePerformance`, `couleur`, `instagram`, `spotify`, `tiktok`, `youtube`) VALUES
(1, 'Freeze Corleone', 'Freeze Corleone, de son vrai nom Issa Lorenzo Diakhaté, est un rappeur français originaire de Seine-Saint-Denis. Membre fondateur du collectif 667, il se distingue par un style sombre et technique, avec des textes riches en références culturelles, historiques et géopolitiques. Son flow froid et précis, combiné à des sonorités trap, lui a permis de se forger une identité unique dans le rap français.\n\nPeu médiatisé, Freeze cultive le mystère et laisse ses morceaux parler pour lui. Son album \"LMF\" (La Menace Fantôme), sorti en 2020, l’a propulsé sur le devant de la scène tout en déclenchant plusieurs polémiques. Aujourd’hui, il est reconnu pour son univers cohérent, son écriture dense et son indépendance artistique.', '/uploads/1746260154283-carte freeze.png', '2025-06-13 00:00:00.000', 'b056d6', 'https://www.instagram.com/bigfreezecorleone667/', 'https://open.spotify.com/intl-fr/artist/76Pl0epAMXVXJspaSuz8im?si=UI-tN2d7QCu1ZNEuiQlqEQ', NULL, 'https://www.youtube.com/@freezecorleone7615'),
(2, 'Kaaris', 'Kaaris, de son vrai nom Okou Gnakouri, est un rappeur français originaire de Sevran, en Seine-Saint-Denis. Il s’est imposé comme une figure incontournable du rap français grâce à son style agressif, sa voix rauque caractéristique et un flow percutant. Révélé au grand public avec son album \"Or Noir\" en 2013, produit en collaboration avec Booba, Kaaris a marqué les esprits par ses textes bruts et violents, portés par des instrumentales puissantes.\r\n\r\nConsidéré comme un pilier du rap hardcore français, il a largement contribué à populariser la trap en France. Malgré des polémiques médiatiques, il reste un artiste influent, connu pour son charisme, ses punchlines mémorables et son impact durable sur la scène rap.', '/uploads/1746260395274-carte  kaaris.png', '2025-06-13 00:00:00.000', '4a3726', 'https://www.instagram.com/kaarisofficiel1/', 'https://open.spotify.com/intl-fr/artist/1ntQKIMIgESKpKoNXVBvQg?si=1y_q72hMRLm_bzPO40cv9w', 'https://www.tiktok.com/@kaarisofficiel1', 'https://www.youtube.com/channel/UCelI_bl2bVS1AFKaZEx44Vw'),
(3, 'Alpha Wann', 'Alpha Wann, aussi appelé Philly Flingo, est un rappeur français originaire de Paris, membre fondateur du collectif 1995. Il est reconnu pour sa technique irréprochable, sa maîtrise des rimes multisyllabiques et son écriture particulièrement ciselée. Son style repose sur un rap pur, sans concession, où chaque mot est soigneusement choisi, ce qui lui vaut une grande reconnaissance dans le milieu.\n\nAprès plusieurs projets en solo, il confirme son statut avec l’album \"Une main lave l\'autre\" (UMLA), salué pour sa qualité artistique. Alpha Wann cultive une indépendance forte, aussi bien dans ses choix musicaux que dans sa communication, ce qui renforce son image de figure respectée et authentique du rap français.', '/uploads/1746260458731-carte alpha wann.png', '2025-06-15 00:00:00.000', '82afb2', 'https://www.instagram.com/alphawann/', 'https://open.spotify.com/intl-fr/artist/7yeFMUrYTY5cAZx0GKXnti?si=OwSOpFZkQ6qEYYQjM755vw', NULL, 'https://www.youtube.com/channel/UCczJMmccv1lIhMVkZ1FBCSQ'),
(4, 'Damso', 'Damso, de son vrai nom William Kalubi Mwamba, est un rappeur belge d’origine congolaise, devenu l’une des figures majeures du rap francophone. Il est reconnu pour sa plume poétique, introspective et souvent provocante, ainsi que pour ses instrumentales planantes et soigneusement travaillées. Révélé au grand public avec l’album \"Batterie Faible\" et son passage au sein du label 92i de Booba, Damso s’est rapidement démarqué par la richesse de son écriture et sa capacité à mêler émotion, noirceur et esthétisme.\n\nSes albums, comme \"Ipséité\" ou \"QALF\", sont salués pour leur cohérence artistique et leur profondeur. À la fois populaire et respecté, Damso s’impose comme un artiste complet, capable d’explorer de nombreux styles tout en gardant une identité forte.', '/uploads/1746260631296-carte damso.png', '2025-06-14 00:00:00.000', 'a19e6d', 'https://www.instagram.com/thedamso/', 'https://open.spotify.com/intl-fr/artist/2UwqpfQtNuhBwviIC0f2ie?si=zesdAF_rRX-f2GOrvX8YFw', NULL, 'https://www.youtube.com/channel/UCxsYR3_7CKZeRfdJpqGxmdw'),
(5, 'Favé', 'Favé est un jeune rappeur français originaire de Villeneuve-Saint-Georges, qui s’est rapidement fait remarquer sur la scène rap grâce à son énergie débordante et son originalité. Révélé par des morceaux comme “URUS”, il mêle des mélodies accrocheuses, des flows variés et des textes sincères, reflétant son quotidien avec fraîcheur et spontanéité.\n\nSon style navigue entre rap mélodique et trap, avec une touche personnelle qui séduit un public de plus en plus large. En peu de temps, Favé s’est imposé comme l’un des talents prometteurs de la nouvelle génération du rap français, porté par une vibe moderne et authentique.', '/uploads/1746260870078-carte fave.png', '2025-06-14 00:00:00.000', 'c24d13', 'https://www.instagram.com/fave.db/', 'https://open.spotify.com/intl-fr/artist/20JMfmzDb5cjHxEoMXXMyY?si=D2NGMFAyQ469NgNDh9ijag', 'https://www.tiktok.com/@fave.db', 'https://www.youtube.com/channel/UC6yKbnMj2JpyaigY16AYQ9Q'),
(6, 'Jeune Lion', 'Jeune Lion est un rappeur franco-ivoirien qui se distingue par un style hybride et audacieux, mêlant rap, reggae, influences afro et sonorités venues du rap américain. Grâce à cette fusion musicale, il crée un univers original, à la fois énergique et mélodique, où les rythmes dansants côtoient des textes ancrés dans son vécu.\n\nSa capacité à mélanger les genres avec authenticité lui permet de se démarquer sur la scène francophone. Porté par une identité forte et une sensibilité musicale assumée, Jeune Lion représente une voix nouvelle et prometteuse du rap afro-français.', '/uploads/1746260926599-carte jeune lion.png', '2025-06-13 00:00:00.000', '740b1d', 'https://www.instagram.com/jeunelion13/', 'https://open.spotify.com/intl-fr/artist/4tTvRdLVGAsJyk9lEEx3Xb?si=rQUZs_hZQR2XCZ5ruJn-oA', NULL, 'https://www.youtube.com/@jeunelion13'),
(7, 'Django', 'Django est un rappeur français reconnu pour ses textes denses, travaillés et riches en références culturelles allant de la littérature au cinéma. Il mêle avec finesse introspection personnelle et critiques sociales, dans un style sombre et percutant. Il s’est fait connaître en 2016 avec le titre “Fichu”, qui a marqué les esprits par son clip cinématographique et son écriture soignée.\n\nPeu médiatisé, Django cultive une image mystérieuse, préférant laisser sa musique parler d’elle-même. Grâce à son univers singulier, il s’est imposé comme une plume à part dans le paysage du rap français.', '/uploads/1746260997148-carte django.png', '2025-06-15 00:00:00.000', '706a99', 'https://www.instagram.com/django_dkz/', 'https://open.spotify.com/intl-fr/artist/5gU8eqolA1bziWv6e3Wjp3?si=u4UoprblTFW_pRkn7xw3EQ', NULL, 'https://www.youtube.com/@djangodkz'),
(8, 'BU$HI', 'Bu$hi est un rappeur français originaire de Lyon, révélé au sein du collectif Lyonzon et du duo Saturn Citizen. Il s’est ensuite lancé dans une carrière solo, affirmant progressivement son style unique et polyvalent. Capable de passer d’une trap sombre à des ballades mélodiques ou des influences 2-step, Bu$hi explore des ambiances variées tout en gardant une identité musicale cohérente.\n\nSon univers, souvent futuriste et planant, séduit une audience à la recherche de sonorités innovantes et de textes à la fois personnels et stylisés. Aujourd’hui, Bu$hi s’impose comme l’un des artistes les plus créatifs de la nouvelle scène rap française.', '/uploads/1746261031811-carte bushi.png', '2025-06-14 00:00:00.000', '415b03', 'https://www.instagram.com/bushi_st/', 'https://open.spotify.com/intl-fr/artist/2GIoAorOnT0Yp1jKyTzW7K?si=CPvH6bO1RBaSqb_DTHgRhA', 'https://www.tiktok.com/@saturnctzn', 'https://www.youtube.com/@SaturnCitizen/'),
(9, 'Jolagreen23', 'Jolagreen23 est un rappeur français récent qui se fait remarquer par son originalité et son approche novatrice du rap. Son style, mélangeant trap et des sonorités modernes, lui permet de se démarquer dans un genre en constante évolution. Ses morceaux sont à la fois percutants et introspectifs, alliant des textes sincères à un flow unique qui capte l’attention dès les premières secondes.\n\nAvec des productions fraîches et un univers personnel, Jolagreen23 s’impose progressivement comme un artiste à suivre, portant une nouvelle énergie dans le rap français.', '/uploads/1746261122746-jolagreen23.png', '2025-06-13 00:00:00.000', '1eb838', 'https://www.instagram.com/jolagreen23/', 'https://open.spotify.com/intl-fr/artist/2jZ78PLlC1PuYKQ2bVwRvz?si=a-l5WFLCRjWEjxMQ3h9o6Q', 'https://www.tiktok.com/@jolagreen23', 'https://www.youtube.com/channel/UC0xgqiZ-jLED1ksuGT_Xx8A'),
(10, 'La Fève', 'La Fève est un rappeur français qui incarne le symbole de la New Wave dans le rap français. Avec son style innovant et son approche avant-gardiste, il s’est imposé comme l\'une des références de cette nouvelle ère musicale. Son univers, où se mêlent des influences modernes et une écriture percutante, reflète une génération en quête de renouveau dans le rap.\n\nEn mélangeant mélodies accrocheuses, beats expérimentaux et une écriture singulière, La Fève a su créer un son unique, porté par une énergie nouvelle. Aujourd’hui, il est considéré comme l’un des pionniers de cette vague musicale, marquant durablement la scène rap française.', '/uploads/1746261161395-carte la feve.png', '2025-06-15 00:00:00.000', 'c1af3a', 'https://www.instagram.com/lafeve7/', 'https://open.spotify.com/intl-fr/artist/2sBKOwN0fSjx39VtL2WpjJ?si=H1MUPFNyRxarl6s7VWv7kQ', NULL, 'https://www.youtube.com/@Blackmen3781'),
(11, 'La Mano 1.9', 'La Mano 1.9 est un rappeur français qui a fait une entrée fracassante sur la scène rap avec un style brut et une énergie incontournable. Mêlant des influences drill et rap de rue, il s’impose par ses textes authentiques, qui racontent sans détour son quotidien et ses réflexions. Sa musique, marquée par des beats percutants et des flows puissants, parle à une génération à la recherche de rap réaliste et sans fard.\n\nBien que relativement récent, La Mano 1.9 séduit par sa capacité à s’impliquer pleinement dans ses morceaux, offrant une véritable immersion dans son univers.', '/uploads/1746261195009-carte la mano.png', '2025-06-14 00:00:00.000', 'c22525', 'https://www.instagram.com/lamano1.9/', 'https://open.spotify.com/intl-fr/artist/78iJ2FMbYAFY3djO4PbWZi?si=o-ZKWX1-TVOpjojPrBcMPw', 'https://www.tiktok.com/@lamanoonenine19', 'https://www.youtube.com/@lamano1.9-officiel'),
(12, 'Laylow', 'Laylow est un rappeur français reconnu pour son univers cybernétique et son style unique, qui fusionne rap, électronique et sonorités futuristes. Avec des albums conceptuels comme \"Trinity\", il a su se démarquer en mêlant innovations musicales et concepts visuels forts, créant ainsi une expérience immersive qui va au-delà de la musique. Son approche artistique se distingue par une recherche constante de nouveaux horizons, où chaque morceau raconte une histoire en lien avec des thèmes technologiques et contemporains.\n\nLaylow est désormais vu comme l’un des artistes les plus avant-gardistes du rap français, porté par une vision originale et un engagement créatif sans compromis.', '/uploads/1746261237795-carte laylow.png', '2025-06-13 00:00:00.000', '71215a', 'https://www.instagram.com/jey.laylow/', 'https://open.spotify.com/intl-fr/artist/0LnhY2fzptb0QEs5Q5gM7S?si=mqNU_AEmSxKM0cxS5pg3hg', NULL, 'https://www.youtube.com/@laylowxsirkloTV'),
(13, 'Luther', 'Luther est un rappeur français au style sombre et introspectif, connu pour sa capacité à mêler mélodies mélancoliques et textes percutants. Il s’est fait remarquer par son écriture mature, où se côtoient réflexions profondes et émotions brutes, dans un univers musical marqué par des influences new wave.\n\nAvec des morceaux où se croisent des sonorités modernes et une poésie sombre, Luther incarne une nouvelle vague du rap français, portée par une authenticité qui touche un public en quête de profondeur et de sincérité.', '/uploads/1746261307572-carte luther.png', '2025-06-15 00:00:00.000', 'f25bd7', 'https://www.instagram.com/lutherantz/', 'https://open.spotify.com/intl-fr/artist/712cOCN3mpraX2UOgUvdHW?si=vAfcFeKFQC-Gz4sGGL5h-Q', NULL, 'https://www.youtube.com/@luther3971'),
(14, 'Nekfeu', 'Nekfeu, de son vrai nom Ken Samaras, est un rappeur français reconnu pour sa plume affûtée et son talent d’écriture exceptionnel. Membre du collectif S-Crew et du groupe 1995, il a su s’imposer comme une figure incontournable du rap français, grâce à des albums acclamés comme \"Feu\" et \"Cyborg\".\n\nNekfeu se distingue par sa capacité à allier sensibilité artistique, technique irréprochable et engagement personnel, abordant des sujets variés allant de l\'introspection aux problématiques sociales. Son approche artistique, à la fois profonde et accessible, en fait l\'un des rappeurs les plus respectés de sa génération.', '/uploads/1746261358075-carte nekfeu.png', '2025-06-14 00:00:00.000', '3ea062', NULL, 'https://open.spotify.com/intl-fr/artist/4LXBc13z5EWsc5N32bLxfH?si=Vw7fYjWTQRaH3xuI-GD5Gg', NULL, 'https://www.youtube.com/@nekfeu4711'),
(15, 'Ninho', 'Ninho est un rappeur français qui s\'est imposé comme l\'une des figures majeures du rap français moderne. Capable de mêler rap pur et mélodies accrocheuses, il séduit un large public grâce à ses morceaux percutants et ses refrains mémorables. Avec des albums à succès comme \"Comme prévu\" et \"Destin\", ainsi que de nombreux disques de platine, il a rapidement consolidé son statut de leader de la scène rap française.\n\nSon flow unique et ses textes réalistes, souvent introspectifs et ancrés dans le quotidien, lui ont permis de toucher une audience variée, faisant de lui l\'un des artistes les plus influents de sa génération.', '/uploads/1746261389292-carte ninho.png', '2025-06-13 00:00:00.000', '5bb7f2', 'https://www.instagram.com/ninhosdt/', 'https://open.spotify.com/intl-fr/artist/6Te49r3A6f5BiIgBRxH7FH?si=KZpWpiQ9SWiCQTA1rv9IBQ', 'https://www.tiktok.com/@ninhosdt', 'https://www.youtube.com/@ninho'),
(16, 'Osirus Jack', 'Osirus Jack est un rappeur français, membre du collectif 667, qui s’est rapidement imposé par son style percutant et sombre. Il se distingue par son originalité, ses punchlines aiguisées et un univers musical où les références culturelles sont omniprésentes. Avec des morceaux intenses et des textes ciselés, il se fait remarquer par sa capacité à manier les mots avec précision, tout en gardant une touche personnelle qui lui est propre.\n\nSa musique, parfois cryptique, plonge l\'auditeur dans un monde dense et complexe, où la réflexion et l’authenticité se mêlent parfaitement, faisant d\'Osirus Jack une voix incontournable du rap français actuel.', '/uploads/1746261418594-carte osirus jack.png', '2025-06-13 00:00:00.000', '7e4b0f', 'https://www.instagram.com/osirusjack667/', 'https://open.spotify.com/intl-fr/artist/3p6dh3Zn4fVXJatMy3Xqzq?si=XZyCUAa8Sz28XnuaaLg0fQ', NULL, 'https://www.youtube.com/@MangemortSquad'),
(17, 'PNL', 'PNL est un duo de rappeurs français composé des frères Ademo et N.O.S.. Ces deux artistes ont révolutionné le rap français en imposant une esthétique unique et un storytelling introspectif qui les distingue des autres. Leur univers, mêlant mélodies envoûtantes et textes profonds, est marqué par une forte dimension émotionnelle et une exploration des thèmes de la solitude, de la famille et des difficultés sociales.\n\nAvec des albums comme \"Dans la légende\" et \"Que la famille\", PNL a créé un phénomène culturel, captivant un large public grâce à des productions innovantes et une approche artistique très personnelle. Leur impact sur la scène rap française est immense, et leur influence va bien au-delà de la musique.', '/uploads/1746261448401-carte pnl.png', '2025-06-14 00:00:00.000', 'ffffff', 'https://www.instagram.com/pnlmusic/', 'https://open.spotify.com/intl-fr/artist/3NH8t45zOTqzlZgBvZRjvB?si=nIuMsDukRZeexZX7HSLPMA', NULL, 'https://www.youtube.com/@pnl'),
(18, 'SCH', 'SCH est un rappeur français qui s’est imposé comme une figure majeure du rap français. Connu pour son style unique mêlant mélancolie, storytelling et une touche d\'esthétisme mafieux, il séduit un large public avec sa voix grave et ses textes intenses, où se mêlent des récits personnels et des réflexions profondes.\n\nAvec des albums à succès comme \"Deo Favente\" et \"JVLIVS\", SCH a su créer un univers singulier, où l’élégance du crime se mêle à une dimension introspective, marquant durablement la scène rap. Son flow maîtrisé et ses productions soignées en font l’un des artistes les plus respectés de sa génération.', '/uploads/1746261478013-carte sch.png', '2025-06-14 00:00:00.000', '7a6c6c', 'https://www.instagram.com/sch/', 'https://open.spotify.com/intl-fr/artist/2kXKa3aAFngGz2P4GjG5w2?si=NlNblB6fSLSLM6mWVkBIsw', 'https://www.tiktok.com/@sch', 'https://www.youtube.com/@sch'),
(19, 'Vald', 'Vald est un rappeur français au style décalé et provocateur, reconnu pour sa capacité à mêler second degré, introspection et absurdité dans ses morceaux. Il a su se faire une place de choix dans le rap français grâce à un univers unique, où les blagues sombres et les réflexions profondes cohabitent.\n\nAvec des albums comme \"Agartha\" et \"XEU\", Vald s’est imposé comme une figure majeure du rap français, attirant à la fois les fans de rap technique et ceux appréciant son côté décalé. Son style particulier, à la fois provocateur et réfléchi, en fait l’un des artistes les plus intéressants et influents de sa génération.', '/uploads/1746261523534-carte vald.png', '2025-06-15 00:00:00.000', '0219c9', 'https://www.instagram.com/valdsullyvan/', 'https://open.spotify.com/intl-fr/artist/3CnCGFxXbOA8bAK54jR8js?si=FUowpSKzT6aHMLVDuxX7Rg', 'https://www.tiktok.com/@valdsullyvan', 'https://www.youtube.com/@ValdSullyvan'),
(20, 'Ziak', 'Ziak est un rappeur français qui s’est imposé avec une entrée fracassante dans le rap, notamment en représentant la drill française. Il est connu pour son univers sombre, ses textes percutants et son identité masquée, qui ajoutent une dimension mystique à son personnage. Avec des morceaux qui plongent l\'auditeur dans un monde urbain intense et sans filtre, Ziak séduit par sa puissance vocale et son flow incisif.\n\nSon style, marqué par des beats lourds et une écriture brutale, lui permet de se démarquer dans la scène drill tout en captivant une large audience avec des sonorités uniques.', '/uploads/1746261553900-carte ziak v2.png', '2025-06-15 00:00:00.000', '4f4d4d', 'https://www.instagram.com/ziakimbo/', 'https://open.spotify.com/intl-fr/artist/2ubn2zwyYaLdHOCKnTouU2?si=JhUqA001Q4KTZ8xa-ww-EQ', NULL, 'https://www.youtube.com/@ZiakCC');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `Artiste`
--
ALTER TABLE `Artiste`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `Artiste`
--
ALTER TABLE `Artiste`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
